language: go
os: linux
dist: xenial
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
go_import_path: github.com/go-macaron/csrf
env:
  - GO111MODULE=on
script: go test -v -cover -race
